name: indexed_db
version: 0.0.6
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Spirals to learn how to use IndexedDB and client-server communication.
homepage: http://ondart.me/
dependencies:
  browser: any
